version: '3.3'

volumes:
  postgres_data:
  media_value:
  static:

services:
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - media_value:/usr/share/nginx/media
      - static:/usr/share/nginx/static
      - ../docs/redoc.html:/usr/share/nginx/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/api/docs/openapi-schema.yml
    depends_on:
      - web
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - media_value:/code/wordly_game_backednd/media
      - static:/code/wordly_game_backednd/static
    depends_on:
      - db
    env_file:
      - ../.env