# Generated by Django 4.0 on 2022-05-15 21:12

import datetime

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date of adding')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is word in use')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='user.user', verbose_name='id_user')),
            ],
            options={
                'verbose_name': 'DayChallenge',
                'verbose_name_plural': 'DayChallenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, unique=True, verbose_name='word value')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': [django.db.models.functions.text.Lower('word')],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name="user's tryes")),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_word', to='wordly_features.daychallenge', verbose_name='hidden word_id')),
                ('word', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_word', to='wordly_features.words', verbose_name='entered word_id')),
            ],
            options={
                'verbose_name': 'UserWord',
                'verbose_name_plural': 'UserWords',
            },
        ),
        migrations.AddField(
            model_name='daychallenge',
            name='word',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='challenge', to='wordly_features.words', verbose_name='entered word'),
        ),
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.UniqueConstraint(fields=('word', 'task'), name='prevention doubling'),
        ),
    ]
