# Generated by Django 4.0 on 2022-05-03 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, unique=True, verbose_name='word value')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is word in use')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': [django.db.models.functions.text.Lower('word')],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='user.user', verbose_name='id_user')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='wordly_features.words', verbose_name='id_word')),
            ],
            options={
                'verbose_name': 'UserWord',
                'verbose_name_plural': 'UserWords',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name="user's score")),
                ('attempt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name="user's tryes")),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='user.user', verbose_name='id_user')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='wordly_features.words', verbose_name='id_word')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Score',
            },
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('player', 'word'), name='the word can be guess only one times'),
        ),
    ]
