# Generated by Django 4.0 on 2022-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_features', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='daychallenge',
            constraint=models.UniqueConstraint(fields=('player', 'word'), name='unique task to player'),
        ),
    ]
