# Generated by Django 4.0 on 2022-05-20 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_features', '0002_daychallenge_unique task to player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daychallenge',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='wordly_features.words', verbose_name='entered word'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='attempt',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='attempt number'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='task',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='wordly_features.daychallenge', verbose_name='hidden word'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='wordly_features.words', verbose_name='entered word'),
        ),
    ]
