# Generated by Django 4.0 on 2022-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_features', '0003_alter_daychallenge_word_alter_userword_attempt_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='daychallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('player',), name='unique_active_player_task'),
        ),
    ]
